In [24]:
import numpy as np
import pandas as pd

## Load

In [11]:
inputs = open("data/day_02.txt", "r").readlines()

## Prepare

In [27]:
signatures = [np.array([int(word) for word in line.split()]) for line in inputs]
signatures[:5]

[array([24, 25, 28, 31, 28]),
 array([41, 44, 45, 48, 49, 50, 50]),
 array([ 5,  8, 10, 13, 15, 16, 17, 21]),
 array([11, 13, 16, 17, 19, 26]),
 array([79, 81, 78, 79, 82, 84])]

## Solution: Puzzle 1

In [55]:
def is_safe(signature: list[int]) -> bool:
    
    signature_rev = signature[::-1]
    diff_forward = signature[1:] - signature[:-1]
    diff_reverse = signature_rev[1:] - signature_rev[:-1]

    # forward
    if ((diff_forward > 0).all()) and ((diff_forward < 4).all()):
        return True

    # reverse
    if ((diff_reverse > 0).all()) and ((diff_reverse < 4).all()):
        return True

    return False

In [59]:
number_of_safe_signatures = np.array(list(map(is_safe, signatures))).sum()
print(f"There are 

379