In [3]:
import numpy as np
import pandas as pd

## Load

In [4]:
inputs = open("data/day_02.txt", "r").readlines()

## Prepare

In [5]:
signatures = [np.array([int(word) for word in line.split()]) for line in inputs]
signatures[:5]

[array([24, 25, 28, 31, 28]),
 array([41, 44, 45, 48, 49, 50, 50]),
 array([ 5,  8, 10, 13, 15, 16, 17, 21]),
 array([11, 13, 16, 17, 19, 26]),
 array([79, 81, 78, 79, 82, 84])]

## Solution: Puzzle 1

In [8]:
def is_safe(signature: list[int]) -> bool:
    
    signature_rev = signature[::-1]
    diff_forward = signature[1:] - signature[:-1]
    diff_reverse = signature_rev[1:] - signature_rev[:-1]

    # forward
    if ((diff_forward > 0).all()) and ((diff_forward < 4).all()):
        return True

    # reverse
    if ((diff_reverse > 0).all()) and ((diff_reverse < 4).all()):
        return True

    return False

In [25]:
number_of_safe_signatures = np.array(list(map(is_safe, signatures))).sum()
print(f"Number of safe signatures: {number_of_safe_signatures}")

Number of safe signatures: 379


## Solution: Puzzle 2

In [40]:
def generate_sub_signatures(signature: np.array) -> list:
    res = []
    for i in range(signature.shape[0]):
        sub_signature = np.delete(signature, i)
        res.append(sub_signature)
    return res

def is_safe_with_sub_signatures(signature: list[int]) -> bool:
    if is_safe(signature):
        return True
    for sub_signature in generate_sub_signatures(signature):
        

In [ ]:
number_of_safe_signatures = np.array(list(map(is_safe, signatures))).sum()
print(f"Number of safe signatures: {number_of_safe_signatures}")

In [41]:
generate_sub_signatures(signatures[0])

[array([25, 28, 31, 28]),
 array([24, 28, 31, 28]),
 array([24, 25, 31, 28]),
 array([24, 25, 28, 28]),
 array([24, 25, 28, 31])]